name: Test Python file

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Texte à envoyer'
        required: true
        default: 'je suis un'

jobs:
  run_script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run my Python file
        run: |
          echo "Message reçu : ${{ github.event.inputs.message }}"
          python mon_fichier.py "${{ github.event.inputs.message }}"
