name: CI build edited Nucleo

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Texte à envoyer'
        required: true
        default: 'je suis un'

jobs:
  build:

    env:
      PY_COLORS: "1"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install -r requirements.txt
        pip install -r .github/workflows/requirements.txt
    - name: Install SeleniumBase
      run: |
        pip install .

    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Check the console scripts interface
      run: |
        seleniumbase
        sbase
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
  
    - name: Install Xvfb et pytesseract
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb tesseract-ocr
        Xvfb :99 -screen 0 1920x1080x24 &
        echo "DISPLAY=:99" >> $GITHUB_ENV

    - name: Run python scraper_axa.py
      run: |
        python .github/workflows/scraper_axa.py --browser=chrome --headed
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      with:
        name: screenshot
        path: |
          full.png
          center.png
   
